SQLMVC99/Controllers/AdminController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SQLMVC99.Models;
using System.Diagnostics;

namespace SQLMVC99.Controllers
{
    public class AdminController : Controller
    {
        private readonly MyDbContext _context;
        public AdminController(MyDbContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Users()
        {
            var UsersInfo = _context.Usernews.ToList();
            return View(UsersInfo);
        }



        [HttpPost]
        public IActionResult Create(IFormCollection form)
        {
            var name = form["Name"];
            var email = form["Email"];
            var password = form["Password"];
            var role = form["Role"];

            var newUser = new Usernew
            {
                Name = name,
                Email = email,
                Password = password,
                Role = role
            };

            _context.Usernews.Add(newUser);
            _context.SaveChanges();

            return RedirectToAction("Users");
        }
        // صفحة تعديل بيانات المستخدم
        public IActionResult Edit(int id)
        {
            var user = _context.Usernews.Find(id);
            if (user == null)
            {
                return NotFound();
            }

            return View(user);
        }
        [HttpPost]
        public IActionResult Edit(int id, Usernew updatedUser)
        {
            if (id != updatedUser.Id)
            {
                return BadRequest();
            }

            var user = _context.Usernews.FirstOrDefault(u => u.Id == id);
            if (user == null)
            {
                return NotFound();
            }

            // Update user details
            user.Name = updatedUser.Name;
            user.Email = updatedUser.Email;
            user.Password = updatedUser.Password;
            user.Role = updatedUser.Role;

            _context.SaveChanges();

            return RedirectToAction("Users");
        }

        public ActionResult Delete(int Id)
        {
            var user = _context.Usernews.Find(Id);
            if (user == null)
            {
                return NotFound();
            }

            _context.Usernews.Remove(user);
            _context.SaveChanges();
            return RedirectToAction("Users");
        }
        //Product management
        public IActionResult Products()
        {
            var ProductsInfo = _context.Products.ToList();
            return View(ProductsInfo);
        }
        [HttpPost]
        public IActionResult CreateProduct(IFormCollection form)
        {
            var name = form["Name"];
            var price = form["Price"];
            var description = form["Description"];
            var file = form.Files["ProductImage"]; 

            string imagePath = null;

            if (file != null && file.Length > 0)
            {
                string uploadsFolder = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "uploads");

                if (!Directory.Exists(uploadsFolder))
                {
                    Directory.CreateDirectory(uploadsFolder);
                }

                string uniqueFileName = $"{Guid.NewGuid()}{Path.GetExtension(file.FileName)}";
                string filePath = Path.Combine(uploadsFolder, uniqueFileName);

                using (var stream = new FileStream(filePath, FileMode.Create))
                {
                    file.CopyTo(stream);
                }

                imagePath = $"/uploads/{uniqueFileName}";
            }

            var newProduct = new Product
            {
                Name = name,
                Price =  price,
                Description = description,
               Image = imagePath 
            };

            _context.Products.Add(newProduct);
            _context.SaveChanges();

            return RedirectToAction("Index");
        }
        public ActionResult EditProduct(int id)
        {
            var product = _context.Products.Find(id);
            if (product == null)
            {
                return NotFound();
            }
            return View( product);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditProduct(int id, Product updatedProduct)
        {
            if (id != updatedProduct.Id)
            {
                return NotFound();
            }

          
                var existingProduct = _context.Products.Find(id);
                if (existingProduct == null)
                {
                    return NotFound();
                }

                existingProduct.Name = updatedProduct.Name;
                existingProduct.Description = updatedProduct.Description;
                existingProduct.Price = updatedProduct.Price;

              _context.SaveChanges();

                return RedirectToAction(nameof(Index));
         
        }
        public ActionResult DeleteProduct(int Id)
        {
            var product =_context.Products.Find(Id);
            if (product == null)
            {
                return NotFound();
            }

            _context.Products.Remove(product);
            _context.SaveChanges();
            return RedirectToAction("Products");
        }


    }
}

SQLMVC99/Controllers/DepartmentController.cs
using Microsoft.AspNetCore.Mvc;
using SQLMVC99.Models;

namespace SQLMVC99.Controllers
{
    public class DepartmentController : Controller
    {
        private readonly MyDbContext _context;

        public DepartmentController()
        {
            
            _context = new MyDbContext();
        }


        public ActionResult Index()
        {
            var Departments = _context.Departments.ToList();
            return View(Departments);
        }
        public ActionResult Create()
          
        {
            Department newDepartment = new Department();
            return View(newDepartment);
        }



        [HttpPost]
        public ActionResult Create(Department newDepartment)
        {
            if (ModelState.IsValid)
            {
                _context.Departments.Add(newDepartment);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(newDepartment);
        }

       






        



        public ActionResult Edit(int id)
        {
            var department = _context.Departments.Find(id);
            if (department == null)
            {
                return NotFound();
            }
            return View(department);
        }

        [HttpPost]
        public ActionResult Edit(int id, Department updatedDepartment)
        {
            if (id != updatedDepartment.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                
                    _context.Update(updatedDepartment);
                    _context.SaveChanges();
                    return RedirectToAction("Index");
              
               
                
                return RedirectToAction(nameof(Index));
            }
            return View(updatedDepartment);
        }

        public ActionResult Delete(int Id)
        {
            var department = _context.Departments.Find(Id);
            if (department == null)
            {
                return NotFound();
            }

            _context.Departments.Remove(department);
            _context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }

        
        public ActionResult Details(int id)
        {
            var department = _context.Departments.Find(id);
            if (department == null)
            {
                return NotFound();
            }
            return View(department);
        }
    }
}

SQLMVC99/Controllers/User1Controller.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.CodeAnalysis.Scripting;
using Microsoft.EntityFrameworkCore;
using SQLMVC99.Models;

namespace SQLMVC99.Controllers
{
    public class User1Controller : Controller
    {
        private readonly MyDbContext _context;

        public User1Controller(MyDbContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            Usernew newUser = new Usernew();
            return View(newUser);
        }
        [HttpPost]
        public IActionResult Register(Usernew user)
        {
            if (ModelState.IsValid)
            {
                if (user.Password != user.ConfirmPassword)
                {
                    ModelState.AddModelError("ConfirmPassword", "The password and confirmation password do not match.");
                    return View("Index");
                }

                _context.Usernews.Add(user);
                _context.SaveChanges();
                return RedirectToAction("Login");
            }

            return View("Index");
        }


        public IActionResult Login()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Login(string Email, string Password)
        {
            // التحقق من وجود المستخدم في قاعدة البيانات
            var user = _context.Usernews.FirstOrDefault(u => u.Email == Email && u.Password == Password);

            if (user != null)
            {
                HttpContext.Session.SetString("UserEmail", user.Email);
                HttpContext.Session.SetString("UserName", user.Name); 
                HttpContext.Session.SetString("UserRole", user.Role);
                HttpContext.Session.SetString("UserPassword", user.Password);



                // التوجيه حسب دور المستخدم
                if (user.Role == "Admin")
                {
                    return RedirectToAction("Index", "Admin");
                }
                else if (user.Role == "User")
                {
                    return RedirectToAction("Index", "Product");
                }
                else
                {
                    return RedirectToAction("Index", "Home");
                }
            }

            ViewBag.ErrorMessage = "Invalid email or password!";
            return View();
        }
        public IActionResult Profile()
        {
            // جلب البيانات من الـ Session
            var userEmail = HttpContext.Session.GetString("UserEmail");
            var userName = HttpContext.Session.GetString("UserName");
            var userRole = HttpContext.Session.GetString("UserRole");
            var userPassword = HttpContext.Session.GetString("UserPassword");


            // إرسال البيانات للـ View باستخدام ViewBag أو Model
            ViewBag.UserEmail = userEmail;
            ViewBag.UserName = userName;
            ViewBag.UserRole = userRole;
            var user = new Usernew
            {
                Email = userEmail,
                Name = userName,
                Role = userRole,
                Password = userPassword

            };
            return View(user);
        }
        public IActionResult EditProfile()
        {
            var userEmail = HttpContext.Session.GetString("UserEmail");

            if (string.IsNullOrEmpty(userEmail))
            {
                return RedirectToAction("Login");
            }

            var user = _context.Usernews.FirstOrDefault(u => u.Email == userEmail);
            if (user == null)
            {
                return NotFound();
            }

            return View("Profile",user);
        }
        [HttpPost]
        public IActionResult EditProfile(Usernew model)
        {
            var userEmail = HttpContext.Session.GetString("UserEmail");
            if (string.IsNullOrEmpty(userEmail))
            {
                return RedirectToAction("Login");
            }

            var user = _context.Usernews.FirstOrDefault(u => u.Email == userEmail);
            if (user == null)
            {
                return NotFound();
            }

            // تحديث بيانات المستخدم
            user.Name = model.Name;
            user.Email = model.Email;

            if (!string.IsNullOrEmpty(model.Password))
            {
                user.Password = model.Password;
            }

            _context.SaveChanges();

            HttpContext.Session.SetString("UserEmail", user.Email);
            HttpContext.Session.SetString("UserName", user.Name);
            HttpContext.Session.SetString("UserRole", user.Role);
            TempData["SuccessMessage"] = "Edit done succesfully!";

            return RedirectToAction("Profile"); 
        }

        public IActionResult Logout()
        {
            HttpContext.Session.Clear();

            return RedirectToAction("Login");
        }


    }
}

SQLMVC99/Controllers/UserController.cs
using Microsoft.AspNetCore.Mvc;
using SQLMVC99.Models;

namespace SQLMVC99.Controllers
{
    public class UserController : Controller
    {
        private readonly MyDbContext _context;

        public UserController()
        {
            _context = new MyDbContext();
        }

        public ActionResult Index()
        {
            var users = _context.Users.ToList();
            return View(users);
        }

        public ActionResult Edit(int id)
        {
            var user = _context.Users.Find(id);
            if (user == null)
            {
                return NotFound();
            }
            return View(user);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, User updatedUser)
        {
            if (id != updatedUser.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(updatedUser);
                    _context.SaveChanges();
                }
                catch (Exception)
                {
                    if (!_context.Users.Any(u => u.Id == id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(updatedUser);
        }

        public ActionResult Delete(int id)
        {
            var user = _context.Users.Find(id);
            if (user == null)
            {
                return NotFound();
            }

            _context.Users.Remove(user);
            _context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }

        public ActionResult Create()
        {
           User newUser = new User();
            return View(newUser);
        }

        [HttpPost]
        public ActionResult Create(User newUser)
        {
            if (ModelState.IsValid)
            {
                _context.Users.Add(newUser);
                _context.SaveChanges();
                return RedirectToAction("Index"); 
            }
            return View(newUser);
        }
    }
}

SQLMVC99/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SQLMVC99</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/SQLMVC99.styles.css" asp-append-version="true" />
    @RenderSection("Style",required:false);
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SQLMVC99</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="User" asp-action="Index">User</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Product" asp-action="Index">Product</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Department" asp-action="Index">Department</a>
                        </li>
                    </ul>

                    <ul class="navbar-nav">
                        @if (Context.Session.GetString("UserEmail") == null)
                        {
                            <!-- المستخدم غير مسجل الدخول -->
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Account" asp-action="Login">Login</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Account" asp-action="Register">Register</a>
                            </li>
                        }
                        else
                        {
                            <!-- المستخدم مسجل الدخول -->
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="User1" asp-action="Profile">
                                    Profile (@Context.Session.GetString("UserEmail"))
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="User1" asp-action="Logout">Logout</a>
                            </li>

                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - SQLMVC99 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" />
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

SQLMVC99/Views/Shared/_Layout1.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewData["Title"]</title>
    @RenderSection("Scripts", required: false)

    @addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/font-awesome/css/font-awesome.min.css" rel="stylesheet">
    <style>
        body {
            background-color: #f4f6f9;
        }

        .sidebar {
            background-color: #343a40;
            min-height: 100vh;
            padding-top: 20px;
        }

            .sidebar a {
                color: #fff;
                padding: 10px 15px;
                text-decoration: none;
                display: block;
            }

                .sidebar a:hover {
                    background-color: #007bff;
                }

        .main-content {
            margin-left: 250px;
            padding: 20px;
        }

        .navbar {
            background-color: #007bff;
        }
    </style>
</head>
<body>

    <!-- Sidebar -->
    <div class="sidebar position-fixed">
        <h3 class="text-white text-center">Admin</h3>
        <a href="#">Dashboard</a>
        <a asp-controller="Admin" asp-action="Users">Users</a>
        <a asp-controller="Admin" asp-action="Products">Products</a>
    </div>

    <!-- Main content -->
    <div class="main-content">
        <!-- Navbar -->
        <nav class="navbar navbar-expand-lg navbar-light">
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                    aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                        <a class="nav-link text-white" asp-controller="User1" asp-action="Logout">Logout</a>
                    </li>
                    <a class="nav-link text-dark" asp-controller="User1" asp-action="Profile">
                        Profile (@Context.Session.GetString("UserEmail"))
                    </a>

                </ul>
            </div>
        </nav>

        <!-- Main content area -->
        @RenderBody()

    </div>

    <!-- Scripts -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.min.js"></script>
</body>
</html>